### ISSUE TITLE
[Android, 1.1.1.37] java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#117] opened 2016-10-27 14:21 UTC
Hello. If keep app in the background (in service), then it crashes. I get feedback from users who are sometimes found with a similar problem. Android version 4.0 - 6.0, jlibtorrent version 1.1.1.37.

logs

```
java.util.concurrent.TimeoutException: com.frostwire.jlibtorrent.swig.session_proxy.finalize() timed out after 10 seconds
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:422)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
at java.lang.Thread.run(Thread.java:818)
```

```
java.util.concurrent.TimeoutException: com.frostwire.jlibtorrent.swig.session.finalize() timed out after 10 seconds
at com.frostwire.jlibtorrent.swig.libtorrent_jni.delete_session(Native Method)
at com.frostwire.jlibtorrent.swig.session.delete(session.java:31)
at com.frostwire.jlibtorrent.swig.session.finalize(session.java:24)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by aldenml** [comment] 2016-10-27 14:48
Hi @proninyaroslav , this is an old version, please, consider updating to `1.1.1.40` if you want to stay in `RC_1_1` of libtorrent branch, but we are moving towards `1.2.0.X` to track libtorrent's `master`.

**Comment by proninyaroslav** [comment] 2016-10-27 14:57
I have the same problem in 1.1.1.40. When about to be released 1.2.0?

**Comment by aldenml** [comment] 2016-10-27 14:58
Fixing a subtle/major bug in `libtorrent` master, but `1.2.0.0` is already out

**Comment by aldenml** [comment] 2016-11-03 16:09
Still a problem? `1.2.0.2` is out

**Comment by aldenml** [comment] 2016-11-07 16:01
I will close this since it's not happening to us with latest version. Feel free to reopen if you keep getting the error. Ideally you should be able to submit a way to reproduce it.

**Comment by proninyaroslav** [comment] 2016-12-08 15:00
I still sometimes get this error when trying to shutdown the app. This doesn't happen often and this error is difficult to track.
My code:
@Override
```
public void onDestroy()
{
       ...
       engine.stop()
       ...
}
```
I stop session at `onDestroy()` method in service.

**Comment by aldenml** [comment] 2016-12-08 15:48
version?

**Comment by proninyaroslav** [comment] 2016-12-08 15:51
1.2.0.4.

**Comment by aldenml** [comment] 2016-12-14 20:42
What class are you using to handle the session? Is it `SessionManager`?

**Comment by proninyaroslav** [comment] 2016-12-15 08:13
@aldenml 
Yes, it's `SessionManager`.

**Comment by aldenml** [comment] 2016-12-15 19:43
I think that since you are calling `engine.stop()` directly in `onDestroy()` you are getting an ANR. Could you confirm if this is indeed the crash?

**Comment by proninyaroslav** [comment] 2016-12-16 14:51
@aldenml 
This happens including when I get magnet link after calling `SessionManager.stop()` (see https://github.com/proninyaroslav/libretorrent/blob/master/app/src/main/java/org/proninyaroslav/libretorrent/core/TorrentFetcher.java#L130)

**Comment by aldenml** [comment] 2016-12-16 15:03
thanks for the link.

This definitely is not the right way to handle `SessionManager`, every time you run `start()/stop()` it recreates a new native `session`, and since this is a shared object library, I would be very cautious. Better to have one instance of `SessionManager` for the entire program execution. You should see the benefits of doing that and maybe the problem goes away.

**Comment by proninyaroslav** [comment] 2016-12-16 15:25
@aldenml 
Yes, I know it's not a very good code, and it will be rewritten, but the problem arises not only in it.

**Comment by aldenml** [comment] 2016-12-16 15:29
well, just to be more clear, I'm not referring to the code quality, just talking about the use of the API, and that's probably more due to the lack of documentation in `jlibtorrent` side.

**Comment by proninyaroslav** [comment] 2016-12-16 15:53
I get this problem not constantly but in all points of code, where session is used.
This occurs in the following situations:

1. Fetching magnet
2. Shutdown app
3. If app worked in background, e.g screen unlock after sleep etc. (It's not always due to this)

**Comment by aldenml** [comment] 2016-12-16 19:05
Ok, I checked all our logs in the google play console and I couldn't find any instance of this crash. Maybe making the `SessionManager` a single instance solve the issue.

**Comment by proninyaroslav** [comment] 2016-12-17 10:18
@aldenml 
I will try to move `SessionManager` in singleton and test it.

**Comment by proninyaroslav** [comment] 2017-01-09 17:29
If device in sleep mode then system calls garbage collection and tries to kill session
http://stackoverflow.com/a/28708351
Is it possible to protect the session?

**Comment by aldenml** [comment] 2017-01-09 17:31
Yes, keep a background service and pin the reference there. If your "main" service is killed, then your application is not surviving anyway.

**Comment by proninyaroslav** [comment] 2017-01-09 17:33
The matter is that the session is already in background service.

**Comment by gubatron** [comment] 2017-01-10 15:25
>The matter is that the session is already in background service.

is this in Android 7?

**Comment by proninyaroslav** [comment] 2017-01-10 15:27
@gubatron 
It occurs in different versions.

**Comment by gubatron** [comment] 2017-01-10 16:27
can you share the code of your service?
for some reason it must be shutting down (which isn't easy)

**Comment by proninyaroslav** [comment] 2017-01-10 16:41
@gubatron 
This occurs when device goes into sleep mode. This behavior is not only in service but also for example when downloading magnet
https://github.com/proninyaroslav/libretorrent/blob/master/app/src/main/java/org/proninyaroslav/libretorrent/core/TorrentFetcher.java#L130

**Comment by gubatron** [comment] 2017-01-10 16:50
ha, looks like you found the issue then, you shouldn't be stopping the session while attempting to fetch a magnet.

**Comment by gubatron** [comment] 2017-01-10 16:53
Session isn't mean to be started or stopped like that, it's too expensive IMO.

**Comment by proninyaroslav** [comment] 2017-01-10 17:28
@gubatron 
I know about it, but the problem occurs and in service.

**Comment by aldenml** [comment] 2017-03-02 19:07
Closing this in favor of a more updated https://github.com/frostwire/frostwire-jlibtorrent/issues/158

**Closed by aldenml** 2017-03-02 19:07 UTC
