### ISSUE TITLE
File progress is zero for all files after force recheck.

### ISSUE THREAD

**Issue by mianharisali** [frostwire/frostwire-jlibtorrent#152] opened 2017-01-24 18:30 UTC
if a torrent is download 50% , and we force recheck  it. after force recheck all file progresses becomes 0.

And if we save resume data and start the session again add that same torrent then it shows correct values.

**Comment by aldenml** [comment] 2017-01-24 18:41
You need to work with the fact that `forceRecheck` is an asynchronous call. What's the sequence of calls you currently have?

**Comment by mianharisali** [comment] 2017-01-24 19:22
this happens when force recheck finishes , after force rechecking if we get file progress it returns zero.

**Comment by aldenml** [comment] 2017-01-24 19:23
how do you know or check that "when force recheck finishes"?

**Comment by mianharisali** [comment] 2017-01-24 19:25
the state goes to downloading from checking.

**Comment by aldenml** [comment] 2017-01-24 19:25
I see, well, I need to check at it then

**Comment by mianharisali** [comment] 2017-01-24 19:29
you can test it  in.
https://github.com/proninyaroslav/libretorrent

download a torrent , let it download some portion like 1 or 2 %.
then force recheck it.
when force recheck finishes , check the file progress , all becomes zero.

i also tested in my app , same behavior.

**Comment by gubatron** [comment] 2017-01-24 20:21
I believe this is what was happening to me last night.
My problem was that I was never getting a `TORRENT_FINISHED` alert, so I figured, maybe a `forceRecheck` will help, but I was still getting a 0% report.

**Comment by mianharisali** [comment] 2017-01-28 08:59
@gubatron i think this issue is in libtorrent. but i am not sure.

**Comment by mianharisali** [comment] 2017-02-19 16:16
@aldenml any update on this issue ?

**Comment by aldenml** [comment] 2017-02-28 19:18
Hi @mianharisali, maybe the problem was fixed inside `libtorrent`, I don't know. I created a unit test for this issue and I can't replicate it. See https://github.com/frostwire/frostwire-jlibtorrent/commit/71cbeb6cb29ce8302144a28077984ddf46131338

Feel free to reopen if you can provide a concrete example or tweak to the test to reproduce it. Thanks for the feedback.

**Closed by aldenml** 2017-02-28 19:18 UTC

**Comment by mianharisali** [comment] 2017-02-28 19:22
@aldenml can you point in which version of jlibtorrent this issue was fixed , so i can test again?

**Comment by aldenml** [comment] 2017-02-28 19:23
can't say, because it probably was a `libtorrent` issue. Try with the latest version, if you still have problems, I can release another `RC` for you (keep in mind that travis is down due to S3 issues)

**Comment by aldenml** [comment] 2017-02-28 19:24
lates version I mean `1.2.0.6-RC4`

**Comment by mianharisali** [comment] 2017-02-28 19:25
@aldenml i tried the RC4 2 days ago , it still had that problem.

**Comment by aldenml** [comment] 2017-02-28 19:27
can you give me a link inside https://github.com/proninyaroslav/libretorrent more close to the logic related to this?

**Comment by mianharisali** [comment] 2017-02-28 19:31
@aldenml i am testing it again , i will post the result in 5 min , i think it is resolved. just give me 5 min.

**Comment by mianharisali** [comment] 2017-02-28 19:35
@aldenml it is resolved thanks :)
