### ISSUE TITLE
JLibtorrent crashes the app with Process exited due to signal (4) error on some Devices (e.g Oppo a37fw) with Android 5 (and its variants)

### ISSUE THREAD

**Issue by vickyoo7** [frostwire/frostwire-jlibtorrent#246] opened 2020-10-31 09:46 UTC
Recently I updated to v1.2.10.0 of the library. But on some Oppo devices (Oppo a37fw) with Android 5 (these devices support 64bit instructions so Play store serves them arm64_v8a libs) my application crashes with Signal 4 (Illegal instruction). If i install the armeabi_v7a version of the apk then it doesn't crash. It was not an issue with v1.2.0.18. Unfortunately the log is very limited, the zygote process itself crashes. This is the only relevant log available in logcat

> W/linker  ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffef5 arg 0xa110
W/linker  ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffffe arg 0xa2b38
W/linker  ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6fffffff arg 0x3
D/TelephonyProvider( 3284): simId = 0
D/TelephonyProvider( 3284): simId = 0
I/Zygote  (  554): Process 8972 exited due to signal (4)
>

**Comment by gubatron** [comment] 2020-11-05 22:21
I'd take a look at changes in our build toolset for the 1.2.10.0 update for the Android Matrix.
I remember we upgraded the linux distro and at least for ubuntu (x64/desktop) we also were forced to update gcc, perhaps this has something to do with this issue.

**Comment by vickyoo7** [comment] 2020-11-07 07:15
> I'd take a look at changes in our build toolset for the 1.2.10.0 update for the Android Matrix.
> I remember we upgraded the linux distro and at least for ubuntu (x64/desktop) we also were forced to update gcc, perhaps this has something to do with this issue.
> 
> I'd try recompiling on your own with the older toolset and testing again.

Thanks. Looking forward to a solution

**Comment by gubatron** [comment] 2021-01-07 04:28
did this issue go away with 1.2.11?

**Comment by vickyoo7** [comment] 2021-01-07 04:31
> did this issue go away with 1.2.11?

Unfortunately no. I was not able to compile the library myself

**Comment by gubatron** [comment] 2021-01-07 05:34
it'd be great if you could test with our build
https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.11.0

**Comment by vickyoo7** [comment] 2021-01-07 05:44
> it'd be great if you could test with our build
> https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.11.0

Sure, will do that and report back

**Comment by vickyoo7** [comment] 2021-01-07 07:08
> it'd be great if you could test with our build
> https://github.com/frostwire/frostwire-jlibtorrent/releases/tag/release%2F1.2.11.0

The user is still facing same issue with 1.2.11.0

**Comment by gubatron** [comment] 2021-01-07 16:37
Thank you @vickyoo7 , let's see how it goes with 1.2.12.

In the meantime I think this can help us find the bug
https://stackoverflow.com/questions/33206409/unused-dt-entry-type-0x1d-arg

**Comment by vickyoo7** [comment] 2021-01-07 16:51
> Thank you @vickyoo7 , let's see how it goes with 1.2.12.
> 
> In the meantime I think this can help us find the bug
> https://stackoverflow.com/questions/33206409/unused-dt-entry-type-0x1d-arg

Thank you for looking into this but I'm not very good with C/C++

**Comment by gubatron** [comment] 2021-01-07 17:00
I think it'll be a matter of tweaking our build script and enabling/disabling some flags for the gcc linker when building ARM

**Comment by gubatron** [comment] 2021-01-07 17:01
however, these are merely warnings

```
W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffef5 arg 0xa110
W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffffe arg 0xa2b38
W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6fffffff arg 0x3
D/TelephonyProvider( 3284): simId = 0
D/TelephonyProvider( 3284): simId = 0
I/Zygote ( 554): Process 8972 exited due to signal (4)
```

We don't know for sure this is the cause of the crash.

More crashlogs would be helpful.

**Comment by vickyoo7** [comment] 2021-01-07 17:12
> however, these are merely warnings
> 
> ```
> W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffef5 arg 0xa110
> W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6ffffffe arg 0xa2b38
> W/linker ( 8972): /data/app/idm.internet.download.manager-1/lib/arm64/libjlibtorrent-1.2.10.0.so: unused DT entry: type 0x6fffffff arg 0x3
> D/TelephonyProvider( 3284): simId = 0
> D/TelephonyProvider( 3284): simId = 0
> I/Zygote ( 554): Process 8972 exited due to signal (4)
> ```
> 
> We don't know for sure this is the cause of the crash.
> 
> More crashlogs would be helpful.

Unfortunately that's the only relevant log available

**Comment by gubatron** [comment] 2021-03-12 23:49
perhaps this bug will be gone too with the new builds (1.2.13.0) re-built and uploaded today March 12, 2021.

**Comment by vickyoo7** [comment] 2021-03-14 18:35
> perhaps this bug will be gone too with the new builds (1.2.13.0) re-built and uploaded today March 12, 2021.

Unfortunately the user is still having the same issue with version 1.2.13.0

**Comment by gubatron** [comment] 2021-08-14 19:19
Please test with 1.2.14.0

**Comment by gubatron** [comment] 2021-09-24 20:15
Closing

**Closed by gubatron** 2021-09-24 20:15 UTC
