### ISSUE TITLE
SOCKS and HTTP proxy doesn't work

### ISSUE THREAD

**Issue by proninyaroslav** [frostwire/frostwire-jlibtorrent#111] opened 2016-09-27 07:51 UTC
Hello. I noticed that the proxy doesn't work with HTTP and UDP trackers. After apply proxy, Session::isListening return false.

**Comment by aldenml** [comment] 2016-09-27 12:33
Let me will review that, we don't do anything especial here, we expose whatever `libtorrent` has

**Comment by proninyaroslav** [comment] 2016-10-07 15:44
@aldenml 
Is it possible to solve this problem?

**Comment by aldenml** [comment] 2016-10-07 16:26
Hi, I was very busy with a crash I in master. I can't give you an ETA, but I will look at it soon

**Comment by aldenml** [comment] 2016-10-11 21:43
Hi @proninyaroslav, I tested it lightly with HTTP proxy and it seems to work. Can you post some example of how to reproduce your problem? To be honest, I'm not very familiar with how `libtorrent` handles the proxy for trackers.

**Comment by gubatron** [comment] 2016-10-11 21:50
I wonder if it's just that libtorrent doesn't support reverse port forwarding on SOCKS.

Reading on the internet:

"Most folks associate SOCKS with outbound connections only. Did you know, it’s also possible to use SOCKS for inbound connections as well?

The SOCKS specification has a `BIND` command. This command creates a listening socket on the far end and binds it to a specific port. It then waits for someone to connect before it returns an acknowledgement to the SOCKS client. The `BIND` command was made to enable FTP data transfer to work over a SOCKS proxy."
[Source](http://blog.cobaltstrike.com/2015/04/02/reverse-port-forward-through-a-socks-proxy/)

we'd have to check if libtorrent makes use of that `BIND` command. It may be not a bug, just an unimplemented feature in libtorrent, unless you've been able to perform some SOCKS tests with C++ and libtorrent, or Python and libtorrent

**Comment by proninyaroslav** [comment] 2016-10-12 15:46
@aldenml 
I tried to run including as example of frostwire app. 
It may be the case in a proxy servers, but I can't work with the Tor connection (using Orbot).

**Comment by aldenml** [comment] 2016-11-03 16:10
Any new status here?

**Comment by alex-druzhinin** [comment] 2016-11-22 05:02
Hi! When using UDP trackers with SOCKS5 proxy I see only CONNECT and BIND commands, and no ASSOCIATE.
Are you using last version of the libtorrent? They did have this bug in old versions.
Current version in github looks good - https://github.com/arvidn/libtorrent/blob/master/src/udp_socket.cpp

**Comment by aldenml** [comment] 2017-01-22 04:30
Fixed in `1.2.0.6-RC1`. More info at https://github.com/arvidn/libtorrent/issues/1373

**Closed by aldenml** 2017-01-22 04:30 UTC
